In [8]:
from starter import rag

query = "How does the agentic loop keep calling the model until it stops?"
answer = rag.rag(query)
print(answer)

{
    "name": "search",
    "context": {
        "trace_id": "0xcb026df972b6579553ccf0862b692a74",
        "span_id": "0x86ea98d39338eff0",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xbebf8382e42f20db",
    "start_time": "2026-07-18T10:49:56.593454Z",
    "end_time": "2026-07-18T10:49:56.596303Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?",
        "num_results": 5
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0xcb026df972b6579553ccf0862b692a74",
        "span_id": "0x785fda1077ee2ece",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xbebf8382e42f20db",
    "start_time": "2026-07-18T10:49:56.597321Z",
    "end_time": "2026-07-18T10:49:58.278351Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "prompt_length": 29842,
        "model": "gpt-5.4-mini",
        "input_tokens": 7111,
        "output_tokens": 131,
        "cost": 0.00114525
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0xcb026df972b6579553ccf0862b692a74",
        "span_id": "0xbebf8382e42f20db",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-18T10:49:56.593404Z",
    "end_time": "2026-07-18T10:49:58.279190Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?"
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
The loop keeps calling the model by using a `while True` loop and checking whether the model returned any `function_call` items.

How it works:
- Send the current `messages` history to the model.
- If the model returns a `function_call`, run the tool and append the tool result to `messages`.
- If it returns only a normal `message`, set `has_function_calls = False`.
- After processing the response, break out of the loop only when `has_function_calls == False`.

So the stop condition is simple: **if the model makes no function calls in that turn, the loop ends.**

In [1]:
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor

provider = TracerProvider()
provider.add_span_processor(
    SimpleSpanProcessor(ConsoleSpanExporter())
)
trace.set_tracer_provider(provider)

tracer = trace.get_tracer("llm-zoomcamp")

In [2]:
from starter import rag

query = "How does the agentic loop keep calling the model until it stops?"
answer = rag.rag(query)
print(answer)

{
    "name": "search",
    "context": {
        "trace_id": "0xec9ec2118fb9caa574a367c117930470",
        "span_id": "0xc82986772def77ae",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xc4c5c7fecc1f575e",
    "start_time": "2026-07-18T10:46:45.937143Z",
    "end_time": "2026-07-18T10:46:45.938104Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?",
        "num_results": 5
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0xec9ec2118fb9caa574a367c117930470",
        "span_id": "0x1a5ff7883b45c66a",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xc4c5c7fecc1f575e",
    "start_time": "2026-07-18T10:46:45.938650Z",
    "end_time": "2026-07-18T10:46:47.721553Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "prompt_length": 29842,
        "model": "gpt-5.4-mini",
        "input_tokens": 7111,
        "output_tokens": 99,
        "cost": 0.00112605
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0xec9ec2118fb9caa574a367c117930470",
        "span_id": "0xc4c5c7fecc1f575e",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-18T10:46:45.937105Z",
    "end_time": "2026-07-18T10:46:47.722510Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?"
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
The agentic loop keeps calling the model inside a `while True` loop.

After each model response, the code checks whether the response contains any `function_call` items:

- if there is a function call, it runs the tool, appends the tool output to `messages`, and loops again;
- if there are no function calls, it `break`s out of the loop.

So the stop condition is simply: **no function calls in the latest response**.

In [9]:
import sqlite3
from opentelemetry.sdk.trace.export import SpanExporter, SpanExportResult


class SQLiteSpanExporter(SpanExporter):

    def __init__(self, db_path="traces.db"):
        self.conn = sqlite3.connect(db_path)
        self.conn.execute("""
            CREATE TABLE IF NOT EXISTS spans (
                name TEXT,
                start_time INTEGER,
                end_time INTEGER,
                input_tokens INTEGER,
                output_tokens INTEGER,
                cost REAL
            )
        """)
        self.conn.commit()

    def export(self, spans):
        for span in spans:
            attrs = dict(span.attributes or {})
            self.conn.execute(
                "INSERT INTO spans VALUES (?, ?, ?, ?, ?, ?)",
                (
                    span.name,
                    span.start_time,
                    span.end_time,
                    attrs.get("input_tokens"),
                    attrs.get("output_tokens"),
                    attrs.get("cost"),
                ),
            )
        self.conn.commit()
        return SpanExportResult.SUCCESS

    def shutdown(self):
        self.conn.close()

    def force_flush(self):
        return True

In [10]:
provider.add_span_processor(
    SimpleSpanProcessor(SQLiteSpanExporter("traces.db"))
)

In [13]:
from starter import rag

query = "How does the agentic loop keep calling the model until it stops?"
answer = rag.rag(query)
print(answer)

{
    "name": "search",
    "context": {
        "trace_id": "0x7136cffff718c63073e9c0196de94ca6",
        "span_id": "0x1a4afb51a9023e49",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xde1e5ac6f6fea0c4",
    "start_time": "2026-07-18T10:56:08.048383Z",
    "end_time": "2026-07-18T10:56:08.050269Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?",
        "num_results": 5
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0x7136cffff718c63073e9c0196de94ca6",
        "span_id": "0x9d6602fa3fb06d1d",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xde1e5ac6f6fea0c4",
    "start_time": "2026-07-18T10:56:08.052261Z",
    "end_time": "2026-07-18T10:56:09.795870Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "prompt_length": 29842,
        "model": "gpt-5.4-mini",
        "input_tokens": 7111,
        "output_tokens": 133,
        "cost": 0.00114645
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0x7136cffff718c63073e9c0196de94ca6",
        "span_id": "0xde1e5ac6f6fea0c4",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-18T10:56:08.048349Z",
    "end_time": "2026-07-18T10:56:09.799040Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?"
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
The loop keeps calling the model by checking whether the model returned any `function_call` items.

- If the response has a function call, your code runs the tool, appends the tool result to `messages`, and continues the `while True` loop.
- If the response has no function calls, `has_function_calls` stays `False`, so the loop hits `break` and stops.

So the exit condition is:

```python
if has_function_calls == False:
    break
```

In short: the model decides whether more tools are needed, and the loop repeats until the model returns a final message with no tool calls.

In [21]:
import pandas as pd

conn = sqlite3.connect("traces.db")
df = pd.read_sql_query("SELECT * FROM spans", conn)
conn.close()

df

,name,start_time,end_time,input_tokens,output_tokens,cost
0,search,1784371902639419000,1784371902641664000,NaN,NaN,NaN
1,llm,1784371902643563000,1784371906008006000,7111.0,91.0,0.001121
2,rag,1784371902639350000,1784371906011893000,NaN,NaN,NaN
3,search,1784372168048383000,1784372168050269000,NaN,NaN,NaN
4,llm,1784372168052261000,1784372169795870000,7111.0,133.0,0.001146
5,rag,1784372168048349000,1784372169799040000,NaN,NaN,NaN
6,search,1784372517547881000,1784372517550395000,NaN,NaN,NaN
7,llm,1784372517553181000,1784372519088468000,7111.0,115.0,0.001136
8,rag,1784372517547833000,1784372519092055000,NaN,NaN,NaN
9,search,1784372530781661000,1784372530784383000,NaN,NaN,NaN
10,llm,1784372530786644000,1784372532400264000,7111.0,118.0,0.001137
11,rag,1784372530781609000,1784372532403139000,NaN,NaN,NaN

In [15]:
conn = sqlite3.connect("traces.db")
duration_by_span = pd.read_sql_query("""
    SELECT name, SUM(end_time - start_time) AS total_duration_ns
    FROM spans
    WHERE name != 'rag'
    GROUP BY name
    ORDER BY total_duration_ns DESC
""", conn)
conn.close()

duration_by_span

     name  total_duration_ns
0     llm         5108052000
1  search            4131000

In [20]:
from starter import rag

query = "How does the agentic loop keep calling the model until it stops?"
answer = rag.rag(query)
print(answer)

{
    "name": "search",
    "context": {
        "trace_id": "0xbab3f5d3455626a15395e267292e074c",
        "span_id": "0x7134620740a70700",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x1c1359511598a4b6",
    "start_time": "2026-07-18T11:02:10.781661Z",
    "end_time": "2026-07-18T11:02:10.784383Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?",
        "num_results": 5
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "llm",
    "context": {
        "trace_id": "0xbab3f5d3455626a15395e267292e074c",
        "span_id": "0xebaab42c7995eea2",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0x1c1359511598a4b6",
    "start_time": "2026-07-18T11:02:10.786644Z",
    "end_time": "2026-07-18T11:02:12.400264Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "prompt_length": 29842,
        "model": "gpt-5.4-mini",
        "input_tokens": 7111,
        "output_tokens": 118,
        "cost": 0.00113745
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
{
    "name": "rag",
    "context": {
        "trace_id": "0xbab3f5d3455626a15395e267292e074c",
        "span_id": "0x1c1359511598a4b6",
        "trace_state": "[]"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2026-07-18T11:02:10.781609Z",
    "end_time": "2026-07-18T11:02:12.403139Z",
    "status": {
        "status_code": "UNSET"
    },
    "attributes": {
        "query": "How does the agentic loop keep calling the model until it stops?"
    },
    "events": [],
    "links": [],
    "resource": {
        "attributes": {
            "telemetry.sdk.language": "python",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.44.0",
            "service.instance.id": "86b7a6ea-fdbb-4b51-872b-2ceeaf298814",
            "service.name": "unknown_service"
        },
        "schema_url": ""
    }
}
It keeps a `while True` loop around the model call.

Each iteration:

1. sends the full `messages` history to the model,
2. checks the response for any `function_call` items,
3. runs those tools and appends the tool outputs to `messages`,
4. sets `has_function_calls = True` if any tool was used.

At the end of the iteration, it breaks only if `has_function_calls == False`.

So the loop stops when the model returns a response with no function calls, meaning it has given its final answer.

In [22]:
conn = sqlite3.connect("traces.db")
llm_tokens = pd.read_sql_query("""
    SELECT input_tokens
    FROM spans
    WHERE name = 'llm'
""", conn)
conn.close()

print(llm_tokens)
print("min:", llm_tokens["input_tokens"].min())
print("max:", llm_tokens["input_tokens"].max())
print("range:", llm_tokens["input_tokens"].max() - llm_tokens["input_tokens"].min())
print("std:", llm_tokens["input_tokens"].std())

   input_tokens
0          7111
1          7111
2          7111
3          7111
min: 7111
max: 7111
range: 0
std: 0.0